export const schemeDatabase = [
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat (PM-JAY)',
    nameHindi: 'आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Health',
    description: 'Health cover of up to ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    annualBenefit: '₹5,00,000',
  },
  {
    id: 'pm-jan-dhan',
    name: 'PM Jan Dhan Yojana',
    nameHindi: 'प्रधानमंत्री जन धन योजना',
    ministry: 'Ministry of Finance',
    category: 'Financial',
    description: 'Zero-balance bank account with RuPay card, overdraft facility, and accident insurance benefits.',
    annualBenefit: '₹10,000',
  },
  {
    id: 'ujjwala-yojana',
    name: 'PM Ujjwala Yojana',
    nameHindi: 'प्रधानमंत्री उज्ज्वला योजना',
    ministry: 'Ministry of Petroleum & Natural Gas',
    category: 'Women & Welfare',
    description: 'Free LPG connection for eligible women from low-income households.',
    annualBenefit: '₹3,600',
  },
  {
    id: 'pm-awas-yojana',
    name: 'PM Awas Yojana (Gramin)',
    nameHindi: 'प्रधानमंत्री आवास योजना',
    ministry: 'Ministry of Rural Development',
    category: 'Housing',
    description: 'Financial assistance to help eligible families build a pucca house in rural areas.',
    annualBenefit: '₹1,20,000',
  },
  {
    id: 'mudra-yojana',
    name: 'PM Mudra Yojana',
    nameHindi: 'प्रधानमंत्री मुद्रा योजना',
    ministry: 'Ministry of Finance',
    category: 'Business',
    description: 'Collateral-free loans for micro and small enterprises to start or grow a business.',
    annualBenefit: '₹50,000',
  },
  {
    id: 'mgnrega',
    name: 'MGNREGA',
    nameHindi: 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम',
    ministry: 'Ministry of Rural Development',
    category: 'Employment',
    description: 'Guaranteed 100 days of wage employment per rural household every year.',
    annualBenefit: '₹50,000',
  },
  {
    id: 'pm-kisan',
    name: 'PM-KISAN',
    nameHindi: 'प्रधानमंत्री किसान सम्मान निधि',
    ministry: 'Ministry of Agriculture',
    category: 'Agriculture',
    description: 'Income support for farmer families through direct bank transfers.',
    annualBenefit: '₹6,000',
  },
  {
    id: 'post-matric-scholarship',
    name: 'Post-Matric Scholarship',
    nameHindi: 'पोस्ट-मैट्रिक छात्रवृत्ति योजना',
    ministry: 'Ministry of Social Justice',
    category: 'Education',
    description: 'Scholarship support for eligible students pursuing studies after class 10.',
    annualBenefit: '₹50,000',
  },
  {
    id: 'atal-pension',
    name: 'Atal Pension Yojana',
    nameHindi: 'अटल पेंशन योजना',
    ministry: 'Ministry of Finance',
    category: 'Pension',
    description: 'A guaranteed pension scheme for workers in the informal sector.',
    annualBenefit: '₹60,000',
  },
  {
    id: 'pm-vishwakarma',
    name: 'PM Vishwakarma',
    nameHindi: 'प्रधानमंत्री विश्वकर्मा योजना',
    ministry: 'Ministry of MSME',
    category: 'Business',
    description: 'Support for artisans and craftspeople with training, toolkit support, and loans.',
    annualBenefit: '₹15,000',
  },
];